website/api/urls.py
from rest_framework.routers import SimpleRouter

from .views import (
    EventViewSet,
    ProjectViewSet,
    # UserViewSet,
)


router = SimpleRouter()
router.register('events', EventViewSet, basename='events')
router.register('projects', ProjectViewSet, basename='projects')

urlpatterns = router.urls

website/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('temp/', include('pages.urls')),
    path('', include('organizations.urls')),
    path('', include('projects.urls')),
    path('api/v1/', include('api.urls')),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
]

website/projects/urls.py
from django.urls import path
from .views import (
    ProjectTableView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectUpdateView,
    duplicate_project,
    ProjectDeleteView,
    EventTableView,
    EventCreateView,
    EventDetailView,
    EventUpdateView,
    duplicate_event,
    EventDeleteView,
    LocationCreateView,
    TextEventInfoView,
)

urlpatterns = [
    path('projects/', ProjectTableView.as_view(), name='project_table'),
    path('projects/new/', ProjectCreateView.as_view(), name='project_create'),
    path('projects/<uuid:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<uuid:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<uuid:pk>/duplicate/', duplicate_project, name='project_duplicate'),
    path('projects/<uuid:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('events/', EventTableView.as_view(), name='event_table'),
    path('events/new/', EventCreateView.as_view(), name='event_create'),
    path('events/<uuid:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('events/<uuid:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<uuid:pk>/duplicate/', duplicate_event, name='event_duplicate'),
    path('events/<uuid:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('events/<uuid:pk>/txt/', TextEventInfoView.as_view(), name='event_txt_info'),
    path('locations/new/', LocationCreateView.as_view(), name='location_create'),

]

website/core/models.py
import uuid
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.contrib.gis.db import models
from multiselectfield import MultiSelectField


class PersistentItem(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Entry(PersistentItem):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=5000, blank=True)
    location = models.CharField(max_length=255, blank=True)
    room = models.CharField(max_length=255, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class ContactDetails(models.Model):
    website = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=50, blank=True)
    contact_person = models.CharField(max_length=255, blank=True)

    class Meta:
        abstract = True


class Ownership(models.Model):
    OWN = 'o'
    COLLABORATION = 'c'
    EXTERNAL = 'e'

    OWNERSHIP_CHOICES = [
        (OWN, _('Own')),
        (COLLABORATION, _('Collaboration')),
        (EXTERNAL, _('External')),
    ]

    ownership = models.CharField(
        max_length=1,
        choices=OWNERSHIP_CHOICES,
        default=OWN,
    )

    class Meta:
        abstract = True


class Status(models.Model):
    PUBLISHED = 'p'
    DRAFT = 'd'
    CANCELLED = 'c'

    STATUS_CHOICES = (
        (PUBLISHED, _('Published')),
        (DRAFT, _('Draft')),
        (CANCELLED, _('Cancelled')),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        default=PUBLISHED,
    )

    class Meta:
        abstract = True


class Type(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    created = models.DateTimeField(default=timezone.now, editable=False)
    modified = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=50)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


class Category(models.Model):
    FIELDS = (
        ('architecture', _('architecture')),
        ('heritage', _('heritage')),
        ('cultural education', _('cultural education')),
        ('ecology', _('ecology')),
        ('cinema', _('cinema')),
        ('photography', _('photography')),
        ('video games', _('video games')),
        ('interdisciplinary', _('interdisciplinary')),
        ('cabaret', _('cabaret')),
        ('cuisine', _('cuisine')),
        ('folk/local culture', _('folk/local culture')),
        ('literature', _('literature')),
        ('fashion', _('fashion')),
        ('music', _('music')),
        ('science', _('science')),
        ('new media', _('new media')),
        ('traveling', _('traveling')),
        ('design', _('desing')),
        ('urban intervension', _('urban intervension')),
        ('craft', _('craft')),
        ('street art', _('street art')),
        ('visual arts', _('visual arts')),
        ('dance', _('dance')),
        ('theatre', _('theatre')),
        ('other', _('other')),
    )

    fields = MultiSelectField(choices=FIELDS, null=True, blank=True)

    AUDIENCES = (
        ('young kids', _('young kids')),
        ('primary school', _('primary school')),
        ('teenagers', _('teenagers')),
        ('students', _('students')),
        ('adults', _('adults')),
        ('seniors', _('seniors')),
        ('all', _('all'))
    )

    audiences = MultiSelectField(choices=AUDIENCES, null=True, blank=True)

    AUDIENCE_GROUPS = (
        ('disadvantaged groups', _('disadvantaged groups')),
        ('people with disabilities', _('people with disabilities')),
        ('district residents', _('district residents')),
        ('pupils', _('pupils')),
        ('artists / creators', _('artists / creators')),
        ('event organizers', _('event organizers')),
        ('ngo representatives', _('ngo representatives')),
        ('educators', _('educators')),
        ('activists', _('activists')),
    )

    audience_groups = MultiSelectField(choices=AUDIENCE_GROUPS, null=True, blank=True)

    MUNICIPAL_PROGRAMS = (
        ('Akacja Lato w mieście', _('Akacja Lato w mieście')),
        ('Akcja Zima w mieście', _('Akcja Zima w mieście')),
        ('Dla seniorów', _('Dla seniorów')),
        ('Katowice bez barier', _('Katowice bez barier')),
        ('Wydarzenie okolicznościowe', _('Wydarzenie okolicznościowe')),
    )

    municipal_programs = MultiSelectField(choices=MUNICIPAL_PROGRAMS, null=True, blank=True)

    class Meta:
        abstract = True


class Location(PersistentItem):
    name = models.CharField(max_length=50)
    coordinates = models.PointField()
    street = models.CharField(max_length=50, blank=True)
    street_number = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    postal_code = models.CharField(max_length=6, blank=True)

    def __str__(self):
        return self.name

website/projects/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from model_clone import CloneMixin

from core.models import (
    Entry,
    Category,
    ContactDetails,
    Ownership,
    Status,
    Type,
    Location,
)
from organizations.models import Activity


class Project(CloneMixin, Entry, ContactDetails, Status):
    parent_project = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    supervisor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    multiple_locations = models.TextField(max_length=1000, blank=True)
    budget = models.IntegerField(null=True, blank=True)
    outside_funding = models.IntegerField(null=True, blank=True)
    outside_funders = models.TextField(max_length=1000, blank=True)

    def get_absolute_url(self):
        return reverse('project_detail', args=[str(self.id)])

    class Meta:
        ordering = ['title']

    @property
    def place(self):
        if self.location:
            return self.location.name
        elif self.multiple_locations:
            return self.multiple_locations
        else:
            return ''


class Event(CloneMixin, Entry, Category, Ownership, Status):
    project = models.ForeignKey(
        Project,
        related_name='events',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    supervisor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
    )
    type = models.ForeignKey(
        Type,
        on_delete=models.SET_NULL,
        null=True,
    )
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    timetable = models.TextField(max_length=2000, blank=True)
    partners = models.TextField(max_length=1000, blank=True)
    online = models.BooleanField(default=False)
    tickets = models.BooleanField(default=False)
    fees = models.CharField(max_length=1000, blank=True)
    particip_num_predict = models.IntegerField(null=True, blank=True)
    particip_num_actual = models.IntegerField(null=True, blank=True)
    link = models.URLField(blank=True)
    registr_link = models.URLField(blank=True)
    budget = models.IntegerField(null=True, blank=True)
    contact_person = models.CharField(max_length=255, blank=True)
    comment = models.TextField(max_length=2000, blank=True)

    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        return reverse('event_detail', args=[str(self.id)])

website/projects/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from mapwidgets.widgets import GooglePointFieldWidget

from .models import Project, Event
from core.models import Location
from organizations.models import Activity


class ProjectForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'char_count', 'data-length': '100'}))
    description = forms.CharField(widget=forms.Textarea(
        attrs={'data-length': '5000'}))

    class Meta:
        model = Project
        exclude = (
            'supervisor',
        )
        help_texts = {
            'multiple_locations': _('Use for multiple locations, e.g. Katowice, Bytom'),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('project_user')
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['activity'].queryset = Activity.objects.filter(
            organization=user.organization)


class EventForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'char_count', 'data-length': '100'}))
    description = forms.CharField(widget=forms.Textarea(
        attrs={'data-length': '5000'}))
    comment = forms.CharField(widget=forms.Textarea(
        attrs={'data-length': '2000'}))

    class Meta:
        model = Event
        exclude = (
            'supervisor',
        )

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        user = request.user
        project_pk = request.GET.get('next')
        super(EventForm, self).__init__(*args, **kwargs)
        if project_pk is not None:
            self.fields['project'].queryset = Project.objects.filter(supervisor=user)
            self.fields['project'].initial = Project.objects.get(pk=project_pk[-37:-1])
        else:
            self.fields['project'].queryset = Project.objects.filter(supervisor=user)


class LocationForm(forms.ModelForm):

    class Meta:
        model = Location
        fields = '__all__'
        widgets = {
            'coordinates': GooglePointFieldWidget,
        }
        labels = {
            "name": _("Name"),
            "coordinates": _(""),
            "street": _("Street"),
            "street_number": _("Street number"),
            "city": _("City"),
            "postal_code": _("Postal code"),
        }

website/templates/event.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load materializecss %}

{% block title %}{% trans "Events" %}{% endblock title %}

{% block content %}

<div class="row">
  <div class="col l8 s12 offset-l2">
    <h1>Event</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.media }}
      {{ form.title|materializecss }}
      <div class="row">
        <div class="col s12 m6">
          {{ form.project|materializecss }}
        </div>
        <div class="col s12 m6">
          {{ form.type|materializecss }}
        </div>
      </div>
      {{ form.description|materializecss:'icon=text_fields' }}
      <div class="row">
        <div class="col s12 m6">
          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">add_location</i>
              <input type="text" id="{{ form.location.name }}" placeholder="" class="autocomplete">
              <label for="autocomplete-input">{{ form.location.label }}</label>
            </div>
            <div class="col s12 add-location-row">
              <a class="waves-effect waves-light btn btn-small modal-trigger grey-30" href="#addLocation">Add location</a>
            </div>
          </div>
        </div>
        {{ form.location }}
        <div class="col s12 m6">
          {{ form.room|materializecss }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m6">
          <div id="{{ form.start_at.name }}">
            <div class="input-field col s12">
              <i class="material-icons prefix">schedule</i>
              <input type="text" id="id_{{ form.start_at.name }}" name="{{ form.start_at.name }}" {% if form.start_at.value %}value="{{ form.start_at.value|date:'Y-m-d H:i' }}"{% endif %} class=" validate">
              <label for="id_{{ form.start_at.name }}">{{ form.start_at.label }}</label>
            </div>
          </div>
        </div>
        <div class="input-field col s12 m6">
          <div id="{{ form.end_at.name }}">
            <div class="input-field col s12">
              <i class="material-icons prefix">schedule</i>
              <input type="text" id="id_{{ form.end_at.name }}" name="{{ form.end_at.name }}" {% if form.end_at.value %}value="{{ form.end_at.value|date:'Y-m-d H:i' }}"{% endif %} class=" validate">
              <label for="id_{{ form.end_at.name }}">{{ form.end_at.label }}</label>
            </div>
          </div>
        </div>
      </div>
      {{ form.timetable|materializecss }}
      <div class="row">
        <div class="col s12 m4">
          {{ form.fields|materializecss }}
        </div>
        <div class="col s12 m4">
          {{ form.audiences|materializecss }}
          {{ form.audience_groups|materializecss }}
          {{ form.municipal_programs|materializecss }}
        </div>
        <div class="col s12 m4">
          <label>Other</label>
          <div class="other_group">
            {{ form.online|materializecss }}
            {{ form.tickets|materializecss }}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          {{ form.ownership|materializecss }}
        </div>
        <div class="col s12 m6">
          {{ form.partners|materializecss }}
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          {{ form.fees|materializecss:'icon=money' }}
        </div>
        <div class="col s12 m6">
          {{ form.budget|materializecss }}
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          {{ form.particip_num_predict|materializecss }}
        </div>
        <div class="col s12 m6">
          {{ form.particip_num_actual|materializecss }}
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          {{ form.link|materializecss:'icon=link' }}
        </div>
        <div class="col s12 m6">
          {{ form.registr_link|materializecss }}
        </div>
      </div>
      {{ form.comment|materializecss }}
      <div class="row">
        <div class="col s12 m6">
          {{ form.status|materializecss:'icon=assignment' }}
        </div>
        <div class="col s12 m6">
          {{ form.contact_person|materializecss:'icon=face' }}
        </div>
      </div>
      <button class="btn waves-effect waves-light btn-margin" type="submit">Save<i class="material-icons right">send</i></button>
    </form>
  </div>
</div>

<!-- Modal Structure -->
<div id="addLocation" class="modal">
    <div class="modal-content">
        <div id="resp">"Loading..."</div>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect btn-flat">"Close"</a>
    </div>
</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;language=en&amp;key=xxxxxxxx"></script>
<script type="text/javascript" src="{% static 'mapwidgets/js/jquery_class.js' %}"></script>
<script type="text/javascript" src="{% static 'mapwidgets/js/django_mw_base.js' %}"></script>
<script type="text/javascript" src="{% static 'mapwidgets/js/mw_google_point_field.js' %}"></script>

<script>
    jQuery(document).ready(function(){

        // Initialize materialize data picker
        var dummyTime = null;
        var currentDateElem = null;
        var dateObj = new Date();

        jQuery('#id_start_at,#id_end_at').datepicker({
            format: 'yyyy-mm-dd',
            onClose: function () {
                currentDateElem = this.el;
                if(currentDateElem.value !== '') {
                    $('body').append('<input type="hidden" id="dummyTime">')
                    dummyTime = $("#dummyTime");
                    dummyTime.timepicker({
                        twelveHour: false,
                        onCloseEnd: function () {
                            var time = dummyTime.val();
                            if (time === '') {
                                time = dateObj.getHours() + ':' + (dateObj.getMinutes() < 10 ? '0' + dateObj.getMinutes() : dateObj.getMinutes() );
                            }
                            currentDateElem.value = currentDateElem.value.replace(/\s\d{2}:\d{2}/, '') + ' ' + time;
                            currentDateElem = null;
                            dummyTime.remove()
                        }
                    });
                    dummyTime.trigger('click');
                }
            }
        });


        $('.modal').modal({
            onCloseEnd: function () {
                $('#resp').html('Loading...')
                loadLocation();
            }
        });

        var mapWidget;
        var location = $('#location');
        var locationSelect = $('#id_location');
        var updateLocations = function (){
            $.ajax(window.location.href, {
                dataType: 'html',
                success: function (resp){
                    locationSelect.replaceWith($(resp).find('#id_location'))
                    locationSelect = $('#id_location')
                    var option = $('#id_location option:last');
                    locationSelect.val(option.val())
                    initLocationSelect()
                    location.val(option.text())
                }
            })
        }
        var loadLocation = function (){
            $.ajax('/locations/new/', {
                dataType: 'html',
                success: function (resp){
                    $("#resp").html($(resp).find('#location_form'))
                }
            })
        }
        loadLocation();

        $(document).on('submit', '#locationForm', function(e){
            e.preventDefault();
            var locationForm = $('#locationForm');
            $.ajax({
                method: "POST",
                url: locationForm.attr('action'),
                data: locationForm.serialize(),
                success: function(resp, status, xhr) {
                    var hasError = $(resp).find('.help-block.orange-text').length
                    if (hasError) {
                        $("#resp").html($(resp).find('#location_form'))
                        mapWidget = new DjangoGooglePointFieldWidget(mapWidgetOptions);
                    } else {
                        updateLocations();
                        $('.modal').modal('close')
                    }
                }
            })
        })

        var initLocationSelect = function () {
            var selectData = {};
            //location.autocomplete('destroy');
            var options = $('#id_location option');
            options.each(function(){
                selectData[$(this).text()] = null;
            })
            location.autocomplete({
                data: selectData,
                onAutocomplete: function(val) {
                    options.each(function(){
                        if($(this).text() === val) {
                            locationSelect.val($(this).val())
                        }
                    })
                }
            });
        }

        var findOption = function (value) {
            var options = $('#id_location option')
            for(var i=0;i<options.length;i++) {
                if($(options[i]).val() === value) {
                    return $(options[i])
                }
            }
            return false;
        }

        initLocationSelect()
        if(locationSelect.val() !== '' && location.val() === '') {
            var option = findOption(locationSelect.val());
            if(option) {
                location.val(option.text())
            }
        }

    });
</script>
{% endblock content %}

website/templates/event_detail.html
{% extends '_base.html' %}
{% load i18n %}

{% block title %}{{ event.title }}{% endblock title %}

{% block content %}

<div id="detail-view" class="row">
  <div class="col s12 no-padding">
    <h1>{{ event.title }}
      {% if event.link %}
      <a href="{{ event.link }}" target="_blank"><i class="material-icons icon-blue small">call_made</i></a>
      {% endif %}
    </h1>

    <div class="row">

      <!-- Left block -->
      <div class="col-block col s12 m6">

        <div class="row display display-header m6">
          <b>{{ event.project }}</b> | {{ event.type }} | <i>{{ event.get_status_display|lower }}</i>
        </div>
        <div class="row display">
          <b>
            {{ event.start_at|date:'d-m-Y H:i' }}{% if event.start_at|date != event.end_at|date %}
            | {{ event.end_at|date:'d-m-Y H:i' }}
            {% else %}–{{ event.end_at|date:'H:i' }}
            {% endif %}
          </b>
        </div>
        <div class="row display">
          {% if event.online %}
            <b>{{ event.online|yesno:"online event,offline event" }}</b>
          {% endif %}
          {% if event.room %}
            | {{ event.location }}
          {% endif %}
          {% if event.room %}
            | {{ event.room }}
          {% endif %}
        </div>
      </div>

      <!-- Right block -->
      <div class="col-block col s12 m4">
        {% if event.fields %}
          <div class="row display display-header no-top-border">
            {{ event.fields }}
          </div>
        {% endif %}
        {% if event.location %}
          <div class="row display">
            {{ event.audiences }}
          </div>
        {% endif %}
        <div class="row display">
          {{ event.tickets|yesno:"tickets: ,free entrance" }}
          {% if event.fees and event.tickets %}
            {{ event.fees }}
          {% endif %}
          {% if event.registr_link %}
            | register or buy tickets <a href="{{ event.registration }}" target="_blank"><i class="material-icons icon-blue tiny">call_made</i></a>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="col-block col s12 m6">
      <div class="row display">
        {{ event.description }}
      </div>
      <div class="row display">
        {{ event.get_ownership_display|lower }} event
        {% if event.partners %}
          {% trans "| partners:" %} {{ event.partners }}
        {% endif %}
      </div>
      {% if event.particip_num_predict or event.particip_num_actual %}
        <div class="row display">
          {% if event.particip_num_predict %}
            participants num | predicted:
            {{ event.particip_num_predict }}
          {% endif %}
          {% if event.particip_num_actual %}
            actual:
            {{ event.particip_num_actual }}
          {% endif %}
        </div>
      {% endif %}
      {% if event.budget %}
        <div class="row display">
          budget: {{ event.budget }} PLN
        </div>
      {% endif %}
      {% if event.comment %}
        <div class="row display">
          <i>{{ event.comment }}</i>
        </div>
      {% endif %}
        <div class="row display no-bottom-border">
          contact person: {{ event.contact_person|default:"<i>not available</i>" }}
        </div>
      </div>

    </div>
    <div class="col s12 m10">
      <div class="row">
        <div class="left">
          <a class='btn-margin waves-effect waves-light btn-small grey-30' href='{% url 'event_txt_info' pk=event.id %}' data-target='event_txt_info'><i class="material-icons left">assignment</i>Copy info</a>
        </div>

        {% if user.is_authenticated and user.groups.all.0.name == 'Coordinator' %}
          <div class="right" style="white-space: nowrap">
            <a href="{% url 'event_update' event.id %}"><i class="material-icons icon-blue">edit</i></a>
            <a href="{% url 'event_duplicate' event.id %}"><i class="material-icons icon-blue">content_copy</i></a>
            <a href="{% url 'event_delete' event.id %}"><i class="material-icons icon-red">delete</i></a>
          </div>
        {% endif %}
      </div>
    </div>

  </div>
</div>

{% endblock content %}

website/templates/event_table.html
{% extends '_base.html' %}
{% load i18n %}
{% load materializecss %}
{% load django_tables2 %}

{% block title %}{% trans "Events" %}{% endblock title %}

{% block content %}

{% if user.groups.all.0.name == 'Coordinator' %}
<div>
  <a href="{% url 'event_table' %}" class="waves-effect waves-light btn-small btn-mini">My events</a>
  <a href="{% url 'organization_event_table' %}" class="waves-effect waves-light btn-small btn-mini">All</a>
</div>
{% endif %}

{% if filter %}
<div class="row">
  <div class="col s12 no-padding">
    <h1>{% trans "Events" %}</h1>
    <form action="" method="get" class="form">
      <div class="row">
        <div class="col s12 m3">
          {{ filter.form.title|materializecss }}
        </div>
        <div class="col s12 m3">
          {{ filter.form.project|materializecss }}
        </div>
        <div class="col s12 m3">
          {{ filter.form.type|materializecss }}
        </div>
        <!-- <div class="col s12 m6">
          <div class="input-field col s12">
            <div id="{{ filter.form.start_at.name }}">
              <input type="text" id="id_{{ filter.form.start_at.name }}" name="{{ filter.form.start_at.name }}" {% if filter.form.start_at.value %}value="{{ filter.form.start_at.value|date:'Y-m-d H:i' }}"{% endif %} class=" validate">
              <label for="id_{{ filter.form.start_at.name }}">{{ filter.form.start_at.label }}</label>
            </div>
          </div>
        </div> -->
        <div class="col s12 m3">
          {{ filter.form.status|materializecss }}
        </div>
      </div>
      <button class="table waves-effect waves-light btn-small grey-30" type="submit" name="button"><i class="material-icons left">search</i>Search</button>
    </form>
  </div>
</div>
{% endif %}

{% render_table table %}

<!-- Export Dropdown -->
<div class="row table-button">
  <a class='dropdown-trigger waves-effect waves-light btn-small grey-30' href='#' data-target='data_export'><i class="material-icons left">arrow_drop_down</i>Export</a>
  <ul id='data_export' class='dropdown-content'>
  {% for format in view.export_formats %}
    <li><a href="{% export_url format %}">{{ format }}</a></li>
  {% endfor %}
  </ul>
</div>

<script>
    jQuery(document).ready(function(){

        // Initialize materialize data picker
        var dummyTime = null;
        var currentDateElem = null;
        var dateObj = new Date();

        jQuery('#id_start_at,#id_end_at').datepicker({
            format: 'yyyy-mm-dd',
            onClose: function () {
                currentDateElem = this.el;
                if(currentDateElem.value !== '') {
                    $('body').append('<input type="hidden" id="dummyTime">')
                    dummyTime = $("#dummyTime");
                    dummyTime.timepicker({
                        twelveHour: false,
                        onCloseEnd: function () {
                            var time = dummyTime.val();
                            if (time === '') {
                                time = dateObj.getHours() + ':' + (dateObj.getMinutes() < 10 ? '0' + dateObj.getMinutes() : dateObj.getMinutes() );
                            }
                            currentDateElem.value = currentDateElem.value.replace(/\s\d{2}:\d{2}/, '') + ' ' + time;
                            currentDateElem = null;
                            dummyTime.remove()
                        }
                    });
                    dummyTime.trigger('click');
                }
            }
        });
    });

</script>

{% endblock content %}

website/templates/home.html
{% extends '_base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Homepage</h1>
{% endblock content %}